name: Build and Deploy Java App to Tomcat (Windows)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    env:
      TOMCAT_HOST: localhost
      TOMCAT_PORT: 8082
      WAR_FILE: DemoProject.war

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean package

      - name: Deploy WAR to Tomcat
        run: |
          $ErrorActionPreference = "Stop"

          $secpasswd = ConvertTo-SecureString "${{ secrets.TOMCAT_PASSWORD }}" -AsPlainText -Force
          $creds = New-Object System.Management.Automation.PSCredential("${{ secrets.TOMCAT_USERNAME }}", $secpasswd)

          Invoke-RestMethod -Uri "http://$env:TOMCAT_HOST:8082/DemoProject&update=true" `
            -Method PUT `
            -InFile "target\$env:WAR_FILE" `
            -Credential $creds `
            -AllowUnencryptedAuthentication
        shell: pwsh
